Many minor cleanups
CrunchyData/crunchy-katacoda pull request #146
Opened 2021-05-03 20:36 UTC by turnstep

2021-05-16 19:02 UTC, keithf4 requested changes

2021-05-16 19:02 UTC, keithf4 commented on pg-administration/basic-postgresql-for-dbas-12/setting-up-pg/05-setup-repo.md
> +sudo yum install -y postgresql12-server postgresql12-contrib
Same as above for why I left the -y out

2021-05-16 19:02 UTC, keithf4 commented on pg-administration/basic-postgresql-for-dbas-12/setting-up-pg/05-setup-repo.md
> +Thankfully the PostgreSQL community provides an RPM repo that contains the latest version of not only postgres but many other popular third-party related tools as well (pgadmin, pgbouncer, pgbackrest
Same as above for period placement

2021-05-16 19:02 UTC, keithf4 commented on pg-administration/basic-postgresql-for-dbas-12/setting-up-pg/10-db-init.md
> +Note that prior to Postgres version, the log directory was called `pg_log`.
Missing the version number

2021-05-16 19:02 UTC, keithf4 commented on pg-administration/postgresql-features/logical-replication/intro.md
> +The default replication process in PostgreSQL is great for high-availability and read-only query distribution. But there are cases where the entire database does not require replication or being able
Same as other comment regarding period placement.

2021-05-25 14:30 UTC, turnstep commented on pg-administration/basic-postgresql-for-dbas-11/setting-up-pg/05-setup-repo.md
> +Thankfully the PostgreSQL community provides an RPM repo that contains the latest version of not only postgres but many other popular third-party related tools as well (pgadmin, pgbouncer, pgbackrest
Well, etc. *always* gets a period right after it, because it is an abbreviation. People vary on the final outer period, however. I'm in the one period camp per above, but some argue for two e.g. `, etc.).`

2021-05-25 14:32 UTC, turnstep commented on pg-administration/basic-postgresql-for-dbas-11/setting-up-pg/05-setup-repo.md
> +sudo yum install -y postgresql11-server postgresql11-contrib
Makes perfect sense, thanks!

2021-05-25 14:44 UTC, turnstep commented on pg-administration/basic-postgresql-for-dbas-12/setting-up-pg/10-db-init.md
> +Note that prior to Postgres version, the log directory was called `pg_log`.
Fixed

2021-05-25 20:29 UTC, merged